config/routes.rb
Rails.application.routes.draw do

  root 'folders#index'
  devise_for :users

  resources :users
  resources :folders do
    member do
      get  'new_file_copy'
      post 'create_file_copy'
      post 'destroy_file'
    end
  end
  resources :security_levels
  resources :permissions
  resources :roles
  resources :role_permissions
  resources :user_roles

end

app/models/folder.rb
class Folder < ActiveRecord::Base

  belongs_to :security_level

  validates :path, presence: true
  validates :security_level_id, presence: true

  def self.list(id, user)
    folders = Array.new

    Folder.all.where.not(id: id).each do |folder|
      if user.can_show?(folder.security_level.lvl)
        folders << folder
      end
    end

    folders
  end

  def self.secure_all(user)
    folders = Array.new

    Folder.all.each do |folder|
      if user.can_show?(folder.security_level.lvl)
        folders << folder
      end
    end

    folders
  end

end

app/models/permission.rb
class Permission < ActiveRecord::Base

  belongs_to :security_level

  validates :name, presence: true

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :permissions

  validates :name, presence: true
end

app/models/role_permission.rb
class RolePermission < ActiveRecord::Base

  has_and_belongs_to_many :roles
  has_and_belongs_to_many :permissions

end

app/models/security_level.rb
class SecurityLevel < ActiveRecord::Base
  validates :lvl, presence: true, numericality: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :roles

  def can_show?(lvl)
    bool = false

    self.roles.each do |role|
      role.permissions.each do |permission|
        if permission.security_level.lvl >= lvl
          bool = bool || permission.show
        elsif !bool
          bool = false
        end
      end
    end

    bool
  end

  def can_copy?(lvl)
    bool = false

    self.roles.each do |role|
      role.permissions.each do |permission|
        if permission.security_level.lvl >= lvl
          bool = bool || permission.copy
        elsif !bool
          bool = false
        end
      end
    end

    bool
  end

  def can_remove?(lvl)
    bool = false

    self.roles.each do |role|
      role.permissions.each do |permission|
        if permission.security_level.lvl >= lvl
          bool = bool || permission.remove
        elsif !bool
          bool = false
        end
      end
    end

    bool
  end



end

app/models/user_role.rb
class UserRole < ActiveRecord::Base

  has_and_belongs_to_many :users
  has_and_belongs_to_many :roles

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_filter :verify_authenticity_token

  before_action :authenticate_user!
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController

  def index
    @folders = Folder.secure_all(current_user)
  end

  def show
    @folder = Folder.find_by_id params[:id]
    @files = Dir.glob(@folder.path + '/**/*')
  end

  def new
    @folder = Folder.new
  end

  def create
    @folder = Folder.new(folder_params)
    if @folder.save
      redirect_to folders_path, notice: 'Директория успешно создана.'
    end
  end

  def edit
    @folder = Folder.find_by_id params[:id]
  end

  def update
    @folder = Folder.find_by_id params[:id]
    if @folder.update_attributes(folder_params)
      redirect_to folders_path, notice: 'Директория успешно обновлена.'
    end
  end

  def destroy
    @folder = Folder.find_by_id(params[:id]).destroy
    redirect_to folders_path, notice: 'Директория успешно удалена.'
  end

  # custom actions

  def new_file_copy
    @current_folder = Folder.find_by_id params[:id]
  end

  def create_file_copy
    old_folder = Folder.find_by_id params[:old_folder_id]
    new_folder = Folder.find_by_id params[:new_folder_id]
    file = params[:file_path]

    # если пытаемся скопировать из более высокого уровня в более низкий
    return (redirect_to folders_path, alert: 'Доступ запрещен.') if old_folder.security_level.lvl > new_folder.security_level.lvl
    return (redirect_to folders_path, alert: 'Доступ запрещен.') unless current_user.can_copy?(new_folder.security_level.lvl)

    FileUtils.cp(file, new_folder.path)
    redirect_to folders_path, notice: 'Файл успешно скопирован.'
  end

  def destroy_file
    File.delete(params[:file_path])
    redirect_to folder_path(params[:current_folder_id]), notice: 'Файл успешно удален.'
  end

  private

    def folder_params
      params.require(:folder).permit!
    end

end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController

  def index
    @permissions = Permission.all
  end

  def show
    @permission = Permission.find_by_id params[:id]
  end

  def new
    @permission = Permission.new
  end

  def create
    @permission = Permission.new(permission_params)
    if @permission.save
      redirect_to permissions_path, notice: 'Разрешение успешно создано.'
    end
  end

  def edit
    @permission = Permission.find_by_id params[:id]
  end

  def update
    @permission = Permission.find_by_id params[:id]
    if @permission.update_attributes(permission_params)
      redirect_to permissions_path, notice: 'Разрешение успешно обновлено.'
    end
  end

  def destroy
    @permission = Permission.find_by_id(params[:id]).destroy
    redirect_to permissions_path, notice: 'Разрешение успешно удалено.'
  end

  private

    def permission_params
      params.require(:permission).permit!
    end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

  def index
    @roles = Role.all
  end

  def show
    @role = Role.find_by_id params[:id]
  end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(role_params)
    if @role.save
      redirect_to roles_path, notice: 'Роль успешно создана.'
    end
  end

  def edit
    @role = Role.find_by_id params[:id]
  end

  def update
    @role = Role.find_by_id params[:id]
    if @role.update_attributes(role_params)
      redirect_to roles_path, notice: 'Роль успешно обновлена.'
    end
  end

  def destroy
    @role = Role.find_by_id(params[:id]).destroy
    redirect_to roles_path, notice: 'Роль успешно удалена.'
  end

  private

    def role_params
      params.require(:role).permit!
    end

end

app/controllers/security_levels_controller.rb
class SecurityLevelsController < ApplicationController

  def index
    @security_levels = SecurityLevel.all
  end

  def show
    @security_level = SecurityLevel.find_by_id params[:id]
  end

  def new
    @security_level = SecurityLevel.new
  end

  def create
    @security_level = SecurityLevel.new(security_level_params)
    if @security_level.save
      redirect_to security_levels_path
    end
  end

  def edit
    @security_level = SecurityLevel.find_by_id params[:id]
  end

  def update
    @security_level = SecurityLevel.find_by_id params[:id]
    if @security_level.update_attributes(security_level_params)
      redirect_to security_levels_path
    end
  end

  def destroy
    @security_level = SecurityLevel.find_by_id(params[:id]).destroy
    redirect_to security_levels_path
  end

  private

    def security_level_params
      params.require(:security_level).permit!
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id params[:id]
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find_by_id params[:id]
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: 'Пользователь успешно создан.'
    end
  end

  def update
    @user = User.find_by_id params[:id]
    if @user.update_attributes(user_params)
      redirect_to users_path, notice: 'Пользователь успешно обновлен.'
    end
  end

  def destroy
    @user = User.find_by_id(params[:id]).destroy
    redirect_to users_path, notice: 'Пользователь успешно удален.'
  end

  private

    def user_params
      params.require(:user).permit!
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/folders/create.slim
= bootstrap_form_for @folder do |f|
  = f.text_field :path
  = f.collection_select(:security_level_id, SecurityLevel.all, :id, :name, :label => 'Уровень секретности', :include_blank => true)
  = f.submit 'Создать'

app/views/folders/edit.slim
= bootstrap_form_for @folder do |f|
  = f.text_field :path
  = f.collection_select(:security_level_id, SecurityLevel.all, :id, :name, :label => 'Уровень секретности', :include_blank => true)
  = f.submit 'Обновить'

app/views/folders/index.slim
table.table.table-hover
  thead
    th Путь
    th Уровень секретности
    th colspan='2' Действия
  tbody
    - @folders.each do |folder|
      tr
        td = link_to folder.path, folder_path(folder.id)
        td = folder.security_level.name
        td = link_to 'Редактировать', edit_folder_path(folder.id)
        - if current_user.can_remove?(folder.security_level.lvl)
          td = link_to 'Удалить', folder_path(folder.id), method: :delete

app/views/folders/new.slim
= bootstrap_form_for @folder do |f|
  = f.text_field :path
  = f.collection_select(:security_level_id, SecurityLevel.all, :id, :name, :label => 'Уровень секретности', :include_blank => true)
  = f.submit 'Создать'

app/views/folders/new_file_copy.slim
= bootstrap_form_tag url: create_file_copy_folder_path do |f|
  = f.collection_select(:new_folder_id, Folder.list(@current_folder.id, current_user), :id, :path, :label => 'Папки', :include_blank => true)
  = f.hidden_field :old_folder_id, value: @current_folder.id
  = f.hidden_field :file_path, value: params[:file_path]
  = f.submit 'Скопировать'

app/views/folders/show.slim
table.table.table-hover
  thead
    th Файл
    th colspan='2' Действия
  tbody
    - @files.each do |file|
      tr
        td = file.split('/').last
        td = link_to 'Копировать', new_file_copy_folder_path(file_path: file)
        - if current_user.can_remove?(@folder.security_level.lvl)
          td = link_to 'Удалить', destroy_file_folder_path(file_path: file, current_folder_id: params[:id]), method: :post

app/views/folders/update.slim
= bootstrap_form_for @folder do |f|
  = f.text_field :path
  = f.collection_select(:security_level_id, SecurityLevel.all, :id, :name, :label => 'Уровень секретности', :include_blank => true)
  = f.submit 'Обновить'

app/views/layouts/application.slim
doctype html
html
  head
    title MBKS
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
  body
    = render 'partials/navigation'
    - if flash.present?
      - flash.each do |name, msg|
        - klass = name == 'alert' ? 'alert-danger' : 'alert-success'
        = content_tag :div, class: "alert #{klass} alert-dismissible mb-10"
          button type="button" class="close" data-dismiss="alert" aria-label="Close"
            span aria-hidden="true"
              | &times
          = msg
    == yield

app/views/partials/_navigation.slim
ul.nav.nav-pills
  li
    a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
      | Директории <span class="caret"></span>
    ul class="dropdown-menu"
      li = link_to 'Список', folders_path
      li = link_to 'Добавить', new_folder_path
  li
    a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
      | Пользователи <span class="caret"></span>
    ul class="dropdown-menu"
      li = link_to 'Список', users_path
  li
    a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
      | Роли <span class="caret"></span>
    ul class="dropdown-menu"
      li = link_to 'Список', roles_path
      li = link_to 'Добавить', new_role_path
  li
    a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
      | Разрешения <span class="caret"></span>
    ul class="dropdown-menu"
      li = link_to 'Список', permissions_path
      li = link_to 'Добавить', new_permission_path
  li
    a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
      | Уровни секретности <span class="caret"></span>
    ul class="dropdown-menu"
      li = link_to 'Список', security_levels_path
      li = link_to 'Добавить', new_security_level_path
  li.right
    - if current_user
      = link_to current_user.email, destroy_user_session_path, method: :delete
    - else
      = link_to 'Войти', new_user_session_path

app/views/permissions/create.slim
= bootstrap_form_for @permission do |f|
  = f.text_field :name
  = f.collection_select(:security_level_id, SecurityLevel.all, :id, :name, :label => 'Уровень секретности', :include_blank => true)
  .row
    .col-xs-3 = f.check_box :show
    .col-xs-3 = f.check_box :copy
    .col-xs-3 = f.check_box :remove
  = f.submit 'Создать'

app/views/permissions/edit.slim
= bootstrap_form_for @permission do |f|
  = f.text_field :name
  = f.collection_select(:security_level_id, SecurityLevel.all, :id, :name, :label => 'Уровень секретности', :include_blank => true)
  .row
    .col-xs-3 = f.check_box :show
    .col-xs-3 = f.check_box :copy
    .col-xs-3 = f.check_box :remove
  = f.submit 'Обновить'

app/views/permissions/index.slim
table.table.table-hover
  thead
    th Название
    th Уровень секретности
    th Чтение
    th Копирование
    th Удаление
    th colspan='2' Действия
  tbody
    - @permissions.each do |permission|
      tr
        td = permission.name
        td = permission.security_level.name
        td = permission.show
        td = permission.copy
        td = permission.remove
        td = link_to 'Редактировать', edit_permission_path(permission.id)
        td = link_to 'Удалить', permission_path(permission.id), method: :delete

app/views/permissions/new.slim
= bootstrap_form_for @permission do |f|
  = f.text_field :name
  = f.collection_select(:security_level_id, SecurityLevel.all, :id, :name, :label => 'Уровень секретности', :include_blank => true)
  .row
    .col-xs-3 = f.check_box :show
    .col-xs-3 = f.check_box :copy
    .col-xs-3 = f.check_box :remove
  = f.submit 'Создать'

app/views/permissions/update.slim
= bootstrap_form_for @permission do |f|
  = f.text_field :name
  = f.collection_select(:security_level_id, SecurityLevel.all, :id, :name, :label => 'Уровень секретности', :include_blank => true)
  .row
    .col-xs-3 = f.check_box :show
    .col-xs-3 = f.check_box :copy
    .col-xs-3 = f.check_box :remove
  = f.submit 'Обновить'

app/views/roles/create.slim
= bootstrap_form_for @role do |f|
  = f.text_field :name
  = f.collection_select(:permission_ids, Permission.all, :id, :name, {:label => 'Разрешения'}, {:multiple => true})
  = f.submit 'Создать'

app/views/roles/edit.slim
= bootstrap_form_for @role do |f|
  = f.text_field :name
  = f.collection_select(:permission_ids, Permission.all, :id, :name, {:label => 'Разрешения'}, {:multiple => true})
  = f.submit 'Обновить'

app/views/roles/index.slim
table.table.table-hover
  thead
    th Название
    th colspan='2' Действия
  tbody
    - @roles.each do |role|
      tr
        td = role.name
        td = link_to 'Редактировать', edit_role_path(role.id)
        td = link_to 'Удалить', role_path(role.id), method: :delete

app/views/roles/new.slim
= bootstrap_form_for @role do |f|
  = f.text_field :name
  = f.collection_select(:permission_ids, Permission.all, :id, :name, {:label => 'Разрешения'}, {:multiple => true})
  = f.submit 'Создать'

app/views/roles/update.slim
= bootstrap_form_for @role do |f|
  = f.text_field :name
  = f.collection_select(:permission_ids, Permission.all, :id, :name, {:label => 'Разрешения'}, {:multiple => true})
  = f.submit 'Обновить'

app/views/security_levels/create.slim
= bootstrap_form_for @security_level do |f|
  = f.text_field :name
  = f.number_field :lvl
  = f.submit 'Создать'

app/views/security_levels/edit.slim
= bootstrap_form_for @security_level do |f|
  = f.text_field :name
  = f.number_field :lvl
  = f.submit 'Обновить'

app/views/security_levels/index.slim
table.table.table-hover
  thead
    th Название
    th Уровень секретности
    th colspan='2' Действия
  tbody
    - @security_levels.each do |security_level|
      tr
        td = security_level.name
        td = security_level.lvl
        td = link_to 'Редактировать', edit_security_level_path(security_level.id)
        td = link_to 'Удалить', security_level_path(security_level.id), method: :delete

app/views/security_levels/new.slim
= bootstrap_form_for @security_level do |f|
  = f.text_field :name
  = f.number_field :lvl
  = f.submit 'Создать'

app/views/security_levels/update.slim
= bootstrap_form_for @security_level do |f|
  = f.text_field :name
  = f.number_field :lvl
  = f.submit 'Обновить'

app/views/users/create.slim
= bootstrap_form_for @user do |f|
  = f.text_field :email
  = f.collection_select(:role_ids, Role.all, :id, :name, {:label => 'Роли'}, {:multiple => true})
  = f.submit 'Создать'

app/views/users/edit.slim
= bootstrap_form_for @user do |f|
  = f.text_field :email
  = f.collection_select(:role_ids, Role.all, :id, :name, {:label => 'Роли'}, {:multiple => true})
  = f.submit 'Обновить'

app/views/users/index.slim
table.table.table-hover
  thead
    th Email
    th Роли
    th colspan='2' Действия
  tbody
    - @users.each do |user|
      tr
        td = user.email
        td = (user.roles.map { |role| (link_to role.name, edit_role_path(role.id)) }).join(', ').html_safe
        td = link_to 'Редактировать', edit_user_path(user.id)
        td = link_to 'Удалить', user_path(user.id), method: :delete

app/views/users/new.slim
= bootstrap_form_for @user do |f|
  = f.text_field :email
  = f.collection_select(:role_ids, Role.all, :id, :name, {:label => 'Роли'}, {:multiple => true})
  = f.submit 'Создать'

app/views/users/update.slim
= bootstrap_form_for @user do |f|
  = f.text_field :email
  = f.collection_select(:role_ids, Role.all, :id, :name, {:label => 'Роли'}, {:multiple => true})
  = f.submit 'Обновить'